name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: jordan-api # Add your deployment name here.
  IMAGE: jordan-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Authenticate with GCR
      uses: google-github-actions/auth@v0.5.0
      with:
        credentials: ${{ secrets.GKE_SA_KEY }}
    
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0.5.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    
    - name: Build Docker image
      run: |
        docker build \
          --tag "us-docker.pkg.dev/cit262-team-01/jordan-api/api-tests:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    
    - name: Push Docker image to GCR
      run: |
        docker push "us-docker.pkg.dev/cit262-team-01/jordan-api/api-tests:latest"
    
    - name: Deploy to GKE cluster
      run: |
        kubectl apply -f dev-manifest.yaml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
